### ISSUE TITLE
Add a sidebar and add chat icon, vertical dots and avatar icon

### ISSUE THREAD

**Issue by tripathi-abhishek** [tripathi-abhishek/whatsapp-clone#1]
For reference, see the picture in README.md

**Comment by sebanti10** [comment]
Can I work on this? I would love to!

**Comment by bh-ramendra** [comment]
I would like to work on it.

**Comment by sebanti10** [comment]
Please do not use labels like "good first issue" or "help wanted" if you are looking forward to adding your own code, it is super confusing for others because we search for such labels...I had literally gone midway of working on this issue..please consider not opening an "issue" if it is self-assigned or use such popular labels, especially during hacktoberfest.
